### ISSUE TITLE
No users configured and authentication has been disabled

### ISSUE THREAD

**Issue by JohnnyPicnic** [hassio-addons/repository-edge#7]
Can't add a user to the config file. Get overwritten every time node red starts.
Config:
{
  "log_level": "info",
  "credential_secret": "************",
  "http_node": {
    "username": "admin",
    "password": "***************"
  },
  "http_static": {
    "username": "admin",
    "password": "*************"
  },
  "port": 1880,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
}

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED v8be1856
 Flow-based programming for the Internet of Things
 From: EDGE - Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / Resin OS 2.3.0+rev1 / HA 0.80.2 / SU 138 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-warning.sh: executing... 
WARNING: No users configured and authentication has been disabled!
WARNING: This is not recommended!!!
[cont-init.d] 11-warning.sh: exited 0.
[cont-init.d] 20-config.sh: executing... 
[cont-init.d] 20-config.sh: exited 0.
[cont-init.d] 30-auto-api-token.sh: executing... 
[cont-init.d] 30-auto-api-token.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-npm-packages.sh: executing... 
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing... 
[cont-init.d] 82-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
> hassio-addon-node-red@1.0.0 start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
20 Oct 15:53:55 - [info] 
Welcome to Node-RED
===================
20 Oct 15:53:55 - [info] Node-RED version: v0.19.4
20 Oct 15:53:55 - [info] Node.js  version: v8.12.0
20 Oct 15:53:55 - [info] Linux 4.4.50 arm LE
20 Oct 15:53:56 - [info] Loading palette nodes
20 Oct 15:54:03 - [info] Settings file  : /etc/node-red/config.js
20 Oct 15:54:03 - [info] Context store  : 'default' [module=memory]
20 Oct 15:54:03 - [info] User directory : /config/node-red/
20 Oct 15:54:03 - [warn] Projects disabled : editorTheme.projects.enabled=false
20 Oct 15:54:03 - [info] Flows file     : /config/node-red/flows.json
20 Oct 15:54:04 - [info] Server now running at https://127.0.0.1:1880/
20 Oct 15:54:04 - [warn] Error loading credentials: SyntaxError: Unexpected token � in JSON at position 0
20 Oct 15:54:04 - [warn] Error loading flows: Error: Failed to decrypt credentials
20 Oct 15:54:04 - [info] Starting flows
20 Oct 15:54:04 - [info] Started flows

**Comment by frenck** [comment]
This is an unreleased developed version and this is expected.
Secondly, please create issues on the correct repo. thanks.
